[package]
name = "retouch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopt = "1.1.3"
globwalk = "0.8.1"
walkdir = "2.3.2"
