name: install-rust-toolchain
description: Install the Rust toolchan (and cache it)

inputs:
  channel:
    description: 'Toolchain channel to use'
    default: stable
  triplet:
    description: 'Toolchain triplet'
outputs:
  availeble-toolchains:
    description: 'Available toolchains'
    value: ${{ steps.list-toolchains.outputs }}
runs:
  using: "composite"
  steps:
    - id: list-toolchains
      run: rustup toolchain list | sed -E 's/([[:graph:]]+)/\1=\1/' >> $GITHUB_OUTPUT
      shell: bash
        