name: install-rust-toolchain
description: Install the Rust toolchan (and cache it)

inputs:
  triplet:
    description: 'Toolchain triplet'
outputs:
  availeble-toolchains:
    description: 'Available toolchains'
    value: ${{ steps.list-toolchains.outputs }}
runs:
  using: "composite"
  steps:
    - id: add-target
      run: rustup target add ${{ inputs.triplet }}
    - id: list-default-toolset
      run: echo "default-toolset=$(rustup default | sed 's/(default)//')" >> $GITHUB_OUTPUT
#      shell: bash
        