name: TestAction
run-name: Test Action

on: workflow_dispatch

jobs:
  test-action:
    name: TestAction
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain-triplet: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc]
    steps:
      - name: cache-toolset
        uses: actions/cache@v3

        env: 
          cache-name: cache-rust-toolset
        with:
          # rust toolset is stored at ~/.rustup/toolchains
          path: ~/.rustup/toolchains
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/manifest-rust-std*') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: List the state of rust toolchains
        continue-on-error: true
        run: rustup target list --installed

      - uses: actions/checkout@v1

      - name: Install
        uses: ./.github/actions/install-rust-toolchain
        with:
          channel: stable
          triplet: ${{ matrix.toolchain-triplet }}

      - name: List the state of rust toolchains
        continue-on-error: true
        run: rustup target list --installed

      - name: Print
        run: echo ${{ steps.Install.output }}